# Generated by Django 4.1.5 on 2023-01-11 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_code", models.CharField(max_length=255)),
                ("phonenumber", models.CharField(max_length=255)),
                ("buytime", models.DateTimeField(auto_now_add=True)),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("1", "1day"),
                            ("7", "7days"),
                            ("15", "15days"),
                            ("30", "30days"),
                            ("60", "60days"),
                        ],
                        default="1",
                        max_length=255,
                    ),
                ),
                ("money_currency", models.IntegerField()),
                (
                    "payment_ok",
                    models.CharField(
                        choices=[("true", "true"), ("false", "false")],
                        default="false",
                        max_length=255,
                    ),
                ),
                (
                    "trackingcode",
                    models.CharField(
                        blank=True, default=uuid.uuid4, max_length=255, unique=True
                    ),
                ),
            ],
        ),
    ]
